app:
  base_url: "https://the-internet.herokuapp.com/login"

browser:
  name: "chrome"
  headless: true
  implicit_wait: 10

api:
  base_url: "http://mock-server:8000"

selenium:
  remote_url: "http://selenium:4444/wd/hub"